spring:
  application:
    name: travel-planner
  profiles:
    active: local
  main:
    allow-bean-definition-overriding: true

server:
  port: 8123
  servlet:
    context-path: /

# springdoc-openapi接口文档配置
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    enabled: true
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.zluolan.zaiagent.controller
  show-actuator: true
  default-flat-param-object: true

# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
  production: false

logging:
  level:
    org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor: debug

